### ISSUE TITLE
Task for April 17 and 24

### ISSUE THREAD

**Issue by chendaniely** [databridgevt/covid19#32]
There's a potential VT news article about the covid project databridge is working on. And we need to put together any tables and graphs you have.

**For April 17:**

1. Create a new issue ( this is where we can keep the conversation for your question/tables/plots contained)
2. The first post of the issue will be what you expect to have by next week (Friday, April 24).
    - Ideally, this is related to the research question posed in #4 
    - It does not need to be fully worked out, preliminary resuts is fine. E.g., I'll be okay even if it's a word count graph or (**shutters**) a word cloud
3. Come back to this post and reply with the issue number you created so it's linked and referenced.

- [x] @gitchrissi
- [x] @Makhsuda
- [x] @sjain1701
- [x] @mitchdolby
- [x] @benrayden37
- [x] @LoveishSarolia

**For April 24:**

- Your table and/or figure can be copy/pasted in the issue you created
- I will expect you to have the code you used ready as well (I will work with you in putting it in the repository)

- [x] @gitchrissi
- [ ] @Makhsuda
- [x] @sjain1701
- [ ] @benrayden37
- [x] @mitchdolby
- [x] @LoveishSarolia

**Comment by mitchdolby** [comment]
#33

**Comment by sjain1701** [comment]
[#34 ](https://github.com/databridgevt/covid19/issues/34)

**Comment by Makhsuda** [comment]
#35

**Comment by gitchrissi** [comment]
#36

**Comment by LoveishSarolia** [comment]
#37

**Comment by chendaniely** [comment]
Closing because the semester is over. The only remainings PRs that need to be worked on are listed in #53
