### ISSUE TITLE
Mitch Dolby Plan for 4/24

### ISSUE THREAD

**Issue by mitchdolby** [databridgevt/covid19#33]
I plan on making visualizations of air quality safety ratings for New York City, Milan, and Wuhan over time and see how they have changed from covid-19 responses. I have csvs on the main types of emissions for each city

**Comment by chendaniely** [comment]
Thanks for letting me know!

I know @datajonbrig pointed me to a data source you were using, but if you need more here's a link to OpenAQ: https://openaq.org/

**Comment by mitchdolby** [comment]
![Milan_NO2](https://user-images.githubusercontent.com/62907620/79899340-a99d7800-83da-11ea-8e25-594d3b4a930f.png)

![NYC_NO2](https://user-images.githubusercontent.com/62907620/79899452-d3569f00-83da-11ea-9cd8-cba5931e977b.png)

![Wuhan_NO2](https://user-images.githubusercontent.com/62907620/79899491-e23d5180-83da-11ea-9300-74ac3ca6e3db.png)

**Comment by chendaniely** [comment]
do you have a list of any major government decisions and their dates? It would be good to see how much lag between key dates and AQ values. Also, why are you just looking at NO_2 values and not all the other readings from AQ sensors?

**Comment by mitchdolby** [comment]
I just started off with NO2 values because it had the most amount data for all three locations, but looking at the changes in the other AQ factors is definitely on my list for future plans, along with looking at the dataset you sent me and seeing if they're consistent with each other. I don't have a list of govt decisions yet, but I'm starting on that now because it's key for context (I also want to know why New York's levels were as low in September as they are now)

**Comment by mitchdolby** [comment]
Here are the fixed graphs

![Milan NO2](https://user-images.githubusercontent.com/62907620/79902332-524dd680-83df-11ea-9a01-6d37cae75941.png)

![NYC NO2](https://user-images.githubusercontent.com/62907620/79902349-57ab2100-83df-11ea-987b-beedc05f2913.png)

![Wuhan NO2](https://user-images.githubusercontent.com/62907620/79902356-5b3ea800-83df-11ea-9a0d-f7a21f2ec1ab.png)

**Comment by chendaniely** [comment]
How much historical data are you able to get?
Anything that spans multiple years? If so you can use that to for seasonal anomoly detection

**Comment by mitchdolby** [comment]
the data can go back to 2014, that would definitely be good for the cities like NYC
