### ISSUE TITLE
Somya's Plan

### ISSUE THREAD

**Issue by sjain1701** [databridgevt/covid19#34]
By April 24, I am planning on having a chart shows how frequently specific risk factors were mentioned in the comm_use_subset. I am planning on doing this through python.
The risk factors I am looking at are pulmonary disease, co-infection, pregnancy, diabetes, and heart disease.

**Comment by chendaniely** [comment]
I've only really used [nltk](https://www.nltk.org/) in the past for these types of tasks, but [spaCy](https://spacy.io/) is one of the newer nlp python libraries.

let me know if you need help with anything (you can always push your code into a branch and I can try running it on my end)

**Comment by sjain1701** [comment]
![riskFactors](https://user-images.githubusercontent.com/62856328/80267680-50e70d00-8670-11ea-8912-0aac5377e56e.png)

**Comment by chendaniely** [comment]
Fixed in #41
