### ISSUE TITLE
Max's plan

### ISSUE THREAD

**Issue by Makhsuda** [databridgevt/covid19#35]
I am planning on looking at frequency of mentioned test kits and beds in articles from comm_use_subset.tsv and try to sort them by states. Using that data I will try to build charts showing states with test kits and beds. I am thinking of using Python and can I have some guidance on how to start, please, as I am still new to Python?

**Comment by chendaniely** [comment]
See the libraries I linked to [here](https://github.com/databridgevt/covid19/issues/34#issuecomment-615348577)

The overall task will be very similar, to Somya's but you'll be working on looking at a different set of words

**Comment by chendaniely** [comment]
Closing because of new semester
