### ISSUE TITLE
Chrissi's Plan

### ISSUE THREAD

**Issue by gitchrissi** [databridgevt/covid19#36]
By April 24, I would like to have worked out how to use the Watson Tone Analyzer API or similar API to analyze the tone of news articles about COVID-19. The news articles will come from the Google News API which I have got working. I will analyze a number of articles and do a count of how many of each resulting tone the articles were written with. I will conclude if the authors are intending on scaring the public when writing their news articles by analyzing what common tones are being used.

**Comment by chendaniely** [comment]
Fixed in #27
