### ISSUE TITLE
Loveish's Plan

### ISSUE THREAD

**Issue by LoveishSarolia** [databridgevt/covid19#37]
I plan to create a visualization based on a variety of stock closing prices and cryptocurrency data that have been specifically affected since the large-scale lockdown caused by coronavirus. I have access to TDAmeritrade's online platform and Coin Metrics which provides accurate, real-time data on a multitude of cryptocurrencies.

**Comment by LoveishSarolia** [comment]
![image](https://user-images.githubusercontent.com/46391911/79905257-f6398100-83e3-11ea-8948-bde5289473c4.png)

**Comment by chendaniely** [comment]
do you have the code for this? could you subit your work+code as a PR?

**Comment by LoveishSarolia** [comment]
> do you have the code for this? could you subit your work+coe as a PR?
What do you mean by coe?

**Comment by chendaniely** [comment]
Sorry mean code (fixed original comment)

**Comment by LoveishSarolia** [comment]
I uploaded the code as a PR, is there anything I need before I close this?

**Comment by chendaniely** [comment]
nope. I'll close it when it #46 gets merged

**Comment by chendaniely** [comment]
Closing because of new semester
