### ISSUE TITLE
Ben's Plan

### ISSUE THREAD

**Issue by benrayden37** [databridgevt/covid19#39]
By 04/24 I intend to analyze the cleaned and compiled pdf.tsv version of the data (thank you dan) in R which contains over 9000 research papers related to covid-19. Firstly, I will clean the data (removing punctuation, capitals, numeral, stop words, etc.) Then, I will generate and list the most frequently used words throughout all of the 9000+ papers. Additionally, I will visualize this data using a stacked bar chart and word-clouds. I will also preform TF-IDF (or: Term Frequency Inverse Document Frequency) over the entire corpus. Finally, I will create A Document Term Correlation Matrix of all the papers.

**Comment by chendaniely** [comment]
Closing because of new semester
