### ISSUE TITLE
Research questions

### ISSUE THREAD

**Issue by chendaniely** [databridgevt/covid19#4]
I realized we might actually run into big problems with code and output all over the repository if we all just `push` directly on `master`. I currently locked the master branch so no changes can be made to it directly.
This also means I get to look through your code as we work on things and we won't affect anyone else in this repository.

Here were the instructions @datajonbrig sent out initially:

- Complete the following guide through chapter 4 (i.e. complete chapters 1-4)
    - head to this link https://www.safaribooksonline.com/library/view/temporary-access/?orpq
        - select "Not listed? click here" and enter your vt email you're in!
        - head to this link: https://learning.oreilly.com/videos/git-essentials-livelessons/9780134655284
- If there were problems playing the safari videos here are linkedin ones for backup
    - https://www.linkedin.com/learning/git-essential-training-the-basics/use-git-version-control-software-to-manage-project-code?u=57888345
    - https://www.linkedin.com/learning/github-essential-training/version-control-and-collaboration-with-github?u=57888345

## Creating a PR with your question/plan

I'm assuming all the commands are being run in your terminal in this projects root folder

1. Create and switch to a new branch: `git checkout -b branch_name` you can name it something like `dan_ques`
2. Create a folder (without spaces or caps) in the `analysis/db` folder, e.g., `dan`
3. Inside this folder create a `README.md` and put down some questions you want to ask from the dataset you downloaded in #3 
4. `add` and `commit` your changes (the `README.md` file you just edited)
5. Send your branch with the commit up to GitHub: `git push origin branch_name`, note you need to use the same branch name from earlier
6. Visit the repo page on GitHub (https://github.com/databridgevt/covid19)
7. A new alert will show up to create a "Pull Request"
    - Create your pull request by clicking through the first page
    - You know you did it correctly when your PR shows up on the PR page: https://github.com/databridgevt/covid19/pulls
    - I'll work with you on your question here and you'll make edits to the `README.md` file until we all settle on a feasible question

- [x] @gitchrissi (#17)
- [x] @Makhsuda (#14)
- [x] @sjain1701 (#10)
- [x] @mitchdolby (#29)
- [x] @benrayden37 (#20)
- [x] @LoveishSarolia (#31)

**Comment by chendaniely** [comment]
If you don't have make instaleld you can also run this command in your environment:

```
conda config --add channels conda-forge
conda config --set channel_priority strict 
```

**Comment by mitchdolby** [comment]
The main research topic that I'm interested in as of now is doing something that analyzes how the environment has rebounded due to human inactivity. I was thinking I could maybe do something related to emissions and focus on a heavily polluted area(s).
