### ISSUE TITLE
Documention + code task for week of April 26 - April 30

### ISSUE THREAD

**Issue by chendaniely** [databridgevt/covid19#42]
Now that you have some sort of preliminary analysis (and many of you would have done your lab presentations now), you can add your presentation to the repository (if you want), but we need to document your work.

Save out the figure into your analysis folder, and add to your readme file answers to these questions:

- What does this figure show?
    - If your figure is technical and uses jargon, explain what those terms mean
- Why did you choose to look at the values shown in the figure?
- Why should someone care about these results?
- What are the limitations/caveats to your data analysis
    - What decisions did you make in the data processing that could under/overestimate your results?
    - What external factors could affect your results?
    - Another way to think about this is this: if you were to present your findings to the public and people are going to take your word to make some actionable decision, what would you tell them could skew the results and affect the decision making?

The sooner you can get these points in the better since there's a VT news article about your work and your documentation could help add context.

Documentation:

- [ ] @gitchrissi
- [ ] @Makhsuda
- [ ] @sjain1701
- [ ] @benrayden37
- [ ] @mitchdolby
- [x] @LoveishSarolia

Code:

- [x] @gitchrissi
- [ ] @Makhsuda
- [x] @sjain1701
- [ ] @benrayden37
- [ ] @mitchdolby
- [x] @LoveishSarolia

**Comment by chendaniely** [comment]
@LoveishSarolia if you're done with your edits please send your branch in as a PR for review

**Comment by LoveishSarolia** [comment]
> @LoveishSarolia if you're done with your edits please send your branch in as a PR for review

Did you see the PR? I never received a confirmation.

**Comment by chendaniely** [comment]
Closing because the semester is over. The only remainings PRs that need to be worked on are listed in #53
